import React from 'react';
import { Composition } from 'remotion';
import { SkitComp } from './skits/Skit';
import { aiTakingMyJob } from './skits/scripts/aiTakingMyJob';
import { aiTakingMyJobPt2 } from './skits/scripts/aiTakingMyJobPt2';
import { lastSongRemembered } from './skits/scripts/lastSongRemembered';
import { visemes as lastSongVisemes } from './skits/scripts/lastSongRemembered.visemes';
import { visemes as aiTakingMyJobVisemes } from './skits/scripts/aiTakingMyJob.visemes';
import { visemes as aiTakingMyJobPt2Visemes } from './skits/scripts/aiTakingMyJobPt2.visemes';
import { withVisemes } from './skits/withVisemes';
import type { Skit } from './skits/types';

/** Register all skits here. Adding a new skit = one line.
 *
 * Each skit that uses voiced `speak` actions is wrapped with
 * `withVisemes` so the generated lip-sync tracks attach at render
 * time. The `*.visemes.ts` files are auto-generated by
 * `npm run generate-voices` — never edit them by hand.
 */
const skits: Skit[] = [
  withVisemes(aiTakingMyJob, aiTakingMyJobVisemes),
  withVisemes(aiTakingMyJobPt2, aiTakingMyJobPt2Visemes),
  withVisemes(lastSongRemembered, lastSongVisemes),
];

export const RemotionRoot: React.FC = () => {
  return (
    <>
      {skits.map((skit) => (
        <Composition
          key={skit.id}
          id={skit.id}
          component={SkitComp as React.FC<Record<string, unknown>>}
          defaultProps={{ skit } as Record<string, unknown>}
          durationInFrames={Math.round(skit.durationInSeconds * (skit.fps ?? 30))}
          fps={skit.fps ?? 30}
          width={skit.width ?? 1080}
          height={skit.height ?? 1920}
        />
      ))}
    </>
  );
};
