/**
 * Pre-generate ElevenLabs voice audio + viseme tracks for each skit.
 *
 * Usage:
 *   npx tsx src/scripts/generateVoices.ts
 *
 * Requires ELEVENLABS_API_KEY in .env (or exported in shell).
 *
 * For each skit, writes:
 *   public/voices/{hash}.mp3
 *   public/voices/{hash}.visemes.json
 *
 * And a single combined module per skit:
 *   src/skits/scripts/{skitFile}.visemes.ts
 *
 * Import that module in Root.tsx and wrap the skit with `withVisemes(...)`.
 */

import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { generateVoice } from '../services/voiceService';
import { aiTakingMyJob } from '../skits/scripts/aiTakingMyJob';
import { aiTakingMyJobPt2 } from '../skits/scripts/aiTakingMyJobPt2';
import { lastSongRemembered } from '../skits/scripts/lastSongRemembered';
import { areYouOkay } from '../skits/scripts/areYouOkay';
import { tedTalk } from '../skits/scripts/tedTalk';
import { widowmaker } from '../skits/scripts/widowmaker';
import { visemeKey } from '../skits/withVisemes';
import type { VisemeFrame } from '../skits/assets';
import type { Skit } from '../skits/types';

type SkitEntry = { skit: Skit; outFile: string };

const SKITS: SkitEntry[] = [
  { skit: aiTakingMyJob, outFile: 'src/skits/scripts/aiTakingMyJob.visemes.ts' },
  { skit: aiTakingMyJobPt2, outFile: 'src/skits/scripts/aiTakingMyJobPt2.visemes.ts' },
  { skit: lastSongRemembered, outFile: 'src/skits/scripts/lastSongRemembered.visemes.ts' },
  { skit: areYouOkay, outFile: 'src/skits/scripts/areYouOkay.visemes.ts' },
  { skit: tedTalk, outFile: 'src/skits/scripts/tedTalk.visemes.ts' },
  { skit: widowmaker, outFile: 'src/skits/scripts/widowmaker.visemes.ts' },
];

async function generateVoicesForSkit({ skit, outFile }: SkitEntry) {
  const speakActions = skit.timeline.filter(
    (a) => a.type === 'speak' && a.voiceId
  ) as Array<Extract<(typeof skit.timeline)[number], { type: 'speak' }>>;

  if (speakActions.length === 0) {
    console.log(`No voiced lines in "${skit.title}".`);
    return;
  }

  console.log(`\n=== ${skit.title} (${speakActions.length} lines) ===`);
  const map: Record<string, { audioUrl: string; visemes: VisemeFrame[] }> = {};

  for (const sp of speakActions) {
    const actor = skit.actors.find((a) => a.id === sp.actorId);
    const label = actor?.name ?? sp.actorId;
    console.log(`  ${label}: "${sp.text.replace(/\n/g, ' ').slice(0, 60)}"`);
    try {
      const { audioUrl, visemes } = await generateVoice({
        voiceId: sp.voiceId!,
        text: sp.text,
        model: sp.voiceModel,
      });
      map[visemeKey(sp.voiceId!, sp.text, sp.voiceModel)] = { audioUrl, visemes };
    } catch (err) {
      console.error(`    ✗ Failed:`, err);
    }
  }

  const code = `// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.\n` +
    `import type { VisemeMap } from '../withVisemes';\n\n` +
    `export const visemes: VisemeMap = ${JSON.stringify(map, null, 2)};\n`;
  fs.writeFileSync(path.resolve(outFile), code);
  console.log(`  → wrote ${outFile}`);
}

async function main() {
  for (const entry of SKITS) {
    await generateVoicesForSkit(entry);
  }
  console.log('\nDone. Import the .visemes.ts file in Root.tsx and wrap with withVisemes(skit, visemes).');
}

main();
