// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "IKne3meq5aSn9XLyUdCD::BRO!! AI is taking EVERYONE’S job!!": {
    "audioUrl": "/voices/HkAwN8FJ_SiOueajGLxcObMV.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.046,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.242,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.358,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.591,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.649,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.73,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.8,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.858,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.904,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.962,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.008,
        "viseme": "Lips_s08_f-v"
      },
      {
        "startSec": 2.043,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.101,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 2.171,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 2.229,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.322,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.357,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 2.38,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.426,
        "viseme": "Lips_s01_sh-ch"
      },
      {
        "startSec": 2.484,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 2.612,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 2.705,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::wait what happened?": {
    "audioUrl": "/voices/tP3WnSYrjgTVraoiXmcDlUaU.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.07,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::They replaced Steve.\nAND Karen.\nAND the intern!!": {
    "audioUrl": "/voices/bz1CXXCEqRfIWs1GPdFYJQOF.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.07,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.104,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_s01_sh-ch"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.964,
        "viseme": "Lips_s08_f-v"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.15,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.394,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.51,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.591,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.649,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.707,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.765,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.916,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.102,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.276,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 2.357,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.45,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 2.508,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.555,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 2.589,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 2.613,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.636,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.694,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 2.74,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.822,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 2.891,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 3.181,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::i think i’m next bro": {
    "audioUrl": "/voices/_xD9pK_q5VjGldozfP39P9lH.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.046,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::...yeah. about that.": {
    "audioUrl": "/voices/Qlq7Y_G_TtLfY26TzhFyHXE0.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 1.057,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.091,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.126,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.149,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.254,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.347,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::I’ve BEEN the AI\nthis whole time, Dave.": {
    "audioUrl": "/voices/6dSfGBRhYj8M4dR1OkhiiVqL.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.07,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_s08_f-v"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.836,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 1.033,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 1.056,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 1.091,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 1.126,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.184,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.23,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.288,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 1.347,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.381,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.59,
        "viseme": "Lips_s08_f-v"
      },
      {
        "startSec": 1.637,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.753,
        "viseme": "Lips_s00_Default"
      }
    ]
  }
};
