// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "IKne3meq5aSn9XLyUdCD::BRO!! AI is taking EVERYONE’S job!!": {
    "audioUrl": "/voices/HkAwN8FJ_SiOueajGLxcObMV.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.10833333333333334,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.21666666666666667,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.138,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.2134999999999998,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.289,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.359,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.4194,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.4798,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.5402,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.6006,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.661,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.753,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.8111428571428572,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.8692857142857142,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.9274285714285715,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.9855714285714285,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.0437142857142856,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.101857142857143,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.16,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.195,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.2065,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.218,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.253,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.353666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.4543333333333335,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.555,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::wait what happened?": {
    "audioUrl": "/voices/tP3WnSYrjgTVraoiXmcDlUaU.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.06566666666666666,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.13133333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.27466666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.31733333333333336,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.46066666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5263333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5920000000000001,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.6576666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_00"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::They replaced Steve.\nAND Karen.\nAND the intern!!": {
    "audioUrl": "/voices/bz1CXXCEqRfIWs1GPdFYJQOF.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.0815,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.2757142857142857,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3304285714285714,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.3851428571428571,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.43985714285714284,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.49457142857142855,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.5492857142857143,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.7805,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.888,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.9955,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.393,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.4666666666666668,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.614,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.684,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.756,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.828,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.9,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.972,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.044,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.287,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.372333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.543,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.589,
        "viseme": "Lips_16"
      },
      {
        "startSec": 2.6414999999999997,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.694,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.763,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.8676,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.0768,
        "viseme": "Lips_05"
      },
      {
        "startSec": 3.1814,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.286,
        "viseme": "Lips_00"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::i think i’m next bro": {
    "audioUrl": "/voices/_xD9pK_q5VjGldozfP39P9lH.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.046,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.104,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.14175,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.1795,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.389,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.4902,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.5274,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.5646,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.6018,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.782,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.902,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::...yeah. about that.": {
    "audioUrl": "/voices/Qlq7Y_G_TtLfY26TzhFyHXE0.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.4005,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.688,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.749,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.81,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.871,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.906,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.9756666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.0453333333333332,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::I’ve BEEN the AI\nthis whole time, Dave.": {
    "audioUrl": "/voices/6dSfGBRhYj8M4dR1OkhiiVqL.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.07,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.2553333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.30166666666666664,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.4065,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.836,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.8823333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.9286666666666666,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.0603333333333333,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.1106666666666667,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2656666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.3353333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.405,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.451,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.575,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.699,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.823,
        "viseme": "Lips_00"
      }
    ]
  }
};
