// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "IKne3meq5aSn9XLyUdCD::BOSS!! Alex is a ROBOT!!": {
    "audioUrl": "/voices/YotsFF9_gHkYr4Gs7nUa3Jc6.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.093,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.952,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 1.347,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 1.463,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.556,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::We know, Dave.": {
    "audioUrl": "/voices/T0UeM_g9KZtBbpuy1__V1sQ2.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.081,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_s08_f-v"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::wait... YOU TOO?!": {
    "audioUrl": "/voices/CHcxsbxU0JwTh7YKhB8E_DSi.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.081,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.964,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::breakroom's out of coffee.\nalso I'm an AI.": {
    "audioUrl": "/voices/We_paiefGoeo2oANBo1R5L4k.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.07,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_s08_f-v"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_s01_sh-ch"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_s08_f-v"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.091,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.66,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.729,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 1.799,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 1.869,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 1.915,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.973,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.996,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.031,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 2.066,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.101,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 2.124,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.147,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.194,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 2.554,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::IS ANYONE HERE REAL?!": {
    "audioUrl": "/voices/h9CaOtk28HrWeKblrKl1LMm0.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.081,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 1.057,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::Just you, Dave.\nJust you.": {
    "audioUrl": "/voices/Yk_W46mSExlbUjbvTdzLIS6W.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s01_sh-ch"
      },
      {
        "startSec": 0.093,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_s08_f-v"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_s01_sh-ch"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 1.033,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 1.08,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 1.231,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 1.324,
        "viseme": "Lips_s00_Default"
      }
    ]
  }
};
