// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "IKne3meq5aSn9XLyUdCD::eleven_flash_v2_5::BRO!! AI is taking EVERYONE’S job!!": {
    "audioUrl": "/voices/BojL_G0r6HfhiCqtDotLzq9g.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.12,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.24,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.207,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.323,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.3984999999999999,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.532,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.5924,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.6528,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.7132,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.7736,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.834,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.892,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.9434285714285713,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.9948571428571427,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.0462857142857143,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.0977142857142854,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.149142857142857,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.200571428571428,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.252,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.287,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.2984999999999998,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.31,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.345,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.445666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.546333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.647,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::wait what happened?": {
    "audioUrl": "/voices/_5gSMuMdwg2cDLIoHJNUmkmA.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.08133333333333333,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.16266666666666665,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.32866666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.36733333333333335,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.5148333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5766666666666667,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.6385,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7003333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_00"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::eleven_flash_v2_5::They replaced Steve.\nAND Karen.\nAND the intern!!": {
    "audioUrl": "/voices/ELCdflfFwdAYt72i4aNpIKwx.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.0755,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.2722857142857143,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.32357142857142857,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.3748571428571429,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.42614285714285716,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.4774285714285714,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.5287142857142857,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.784,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.9059999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.028,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.15,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.301,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.382,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.544,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.626,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.7002,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.7744,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.8486,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.9228,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.997,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.137,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.249,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.473,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.589,
        "viseme": "Lips_16"
      },
      {
        "startSec": 2.6704999999999997,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.752,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.833,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.9328000000000003,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.1324,
        "viseme": "Lips_05"
      },
      {
        "startSec": 3.2321999999999997,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.332,
        "viseme": "Lips_00"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::eleven_flash_v2_5::i think i’m next bro": {
    "audioUrl": "/voices/fJoAgakLiilpHH_UHO9kz6RJ.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.15375,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.1915,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.40049999999999997,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.5178,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.5596,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.6014,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.6432,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8516666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.9833333333333334,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::...yeah. about that.": {
    "audioUrl": "/voices/Ry2SJKaxj_TDk9iWL9wnjond.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3135,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.6970000000000001,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.871,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.906,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.9793333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.0526666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.126,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::I’ve BEEN the AI\nthis whole time, Dave.": {
    "audioUrl": "/voices/YTkSxXuQRJu_Pg9BSbQ1Os_i.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.25166666666666665,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.29433333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.4065,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.836,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.8823333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.9286666666666666,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.064,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.1179999999999999,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.172,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2693333333333332,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.3426666666666667,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.416,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.463,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.579,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.695,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.811,
        "viseme": "Lips_00"
      }
    ]
  }
};
