// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "IKne3meq5aSn9XLyUdCD::eleven_flash_v2_5::BOSS!! Alex is a ROBOT!!": {
    "audioUrl": "/voices/qZKHYwz4xheK5CG_d4lZO3r_.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.13933333333333334,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.2786666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.6477999999999999,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.7036,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7594,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.8151999999999999,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.871,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.9575,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.998,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.033,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.057,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.2102,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.3054,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.4005999999999998,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.4958,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.591,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::We know, Dave.": {
    "audioUrl": "/voices/AaFUitZ8_ZIWLWfdP17JKAnI.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.0815,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.2905,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.5416666666666666,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.6423333333333333,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_00"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::eleven_flash_v2_5::wait... YOU TOO?!": {
    "audioUrl": "/voices/3G8kJY9z0LKT6GeByIhZ7N6S.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.07733333333333334,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.15466666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.424,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.6615,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::breakroom's out of coffee.\nalso I'm an AI.": {
    "audioUrl": "/voices/h9OtlDPxrZ8_rZNNQN8NB6p5.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.0418,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.0836,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.12539999999999998,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.1672,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.25079999999999997,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.3344,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.3762,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.49350000000000005,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.792,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.911,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.03,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.149,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.787,
        "viseme": "Lips_03"
      },
      {
        "startSec": 1.85975,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.9324999999999999,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.0052499999999998,
        "viseme": "Lips_08"
      },
      {
        "startSec": 2.078,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.147,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.1935000000000002,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.24,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.275,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.3040000000000003,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.333,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.391,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.751,
        "viseme": "Lips_00"
      }
    ]
  },
  "IKne3meq5aSn9XLyUdCD::eleven_flash_v2_5::IS ANYONE HERE REAL?!": {
    "audioUrl": "/voices/1TX_VBZiiFcsK6VQOvyfL4yl.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.087,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.27116666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.32133333333333336,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.37150000000000005,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.4216666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.4718333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.522,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.6113333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6656666666666666,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.8863333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.9946666666666667,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Just you, Dave.\nJust you.": {
    "audioUrl": "/voices/7T8ASawSVanhVyklwsUdjw9Y.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.06375,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.1275,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.19125,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3715,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.561,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.623,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.839,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.9610000000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.08,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1724999999999999,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.265,
        "viseme": "Lips_00"
      }
    ]
  }
};
