// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::...babe?": {
    "audioUrl": "/voices/Rpp5CGXWPTGYMdLeh7QDstaR.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.3983333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5416666666666667,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_20"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::Are you mad at me?": {
    "audioUrl": "/voices/FBU0WC76fwNB98QgKK5q58nc.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.0695,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.3403333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.39066666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.505,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.6619999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_20"
      }
    ]
  },
  "onwK4e9ZLuTAKqWW03F9::eleven_flash_v2_5::No.": {
    "audioUrl": "/voices/EtfUWIHhyapyJ2vL1U6b3zq3.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.1275,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_20"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::What are you thinking about.": {
    "audioUrl": "/voices/IUDY2eopDYZNsLhf8g9Sb25w.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.05433333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.10866666666666668,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.2205,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3135,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.4295,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.47600000000000003,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.5690000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6155,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7805,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.853,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.9255,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.998,
        "viseme": "Lips_20"
      }
    ]
  },
  "onwK4e9ZLuTAKqWW03F9::eleven_flash_v2_5::If a hot dog is a sandwich.": {
    "audioUrl": "/voices/0kS51rG7toGV6tLX2ufEo3UE.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.0695,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.32133333333333336,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.37566666666666665,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.565,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.654,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.068,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.155,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.242,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.289,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.324,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.382,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.4582857142857142,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.5345714285714285,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.687142857142857,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.7634285714285713,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.8397142857142856,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.916,
        "viseme": "Lips_20"
      }
    ]
  },
  "onwK4e9ZLuTAKqWW03F9::eleven_flash_v2_5::I've decided it isn't.": {
    "audioUrl": "/voices/Q46pLfHgEBODMjUD35QeLi8a.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.1105,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.3152857142857143,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.38657142857142857,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.45785714285714285,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.5291428571428571,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.6004285714285714,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6717142857142857,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8765,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.94,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.0774,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.1448,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.2122,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.347,
        "viseme": "Lips_20"
      }
    ]
  }
};
