// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "cgSgspJ2msm6clMCkdW9::...babe?": {
    "audioUrl": "/voices/mXfJkGzZ9bC0seWCnCvs_mrb.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.4103333333333333,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.5186666666666666,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::Are you mad at me?": {
    "audioUrl": "/voices/RFst644deXqXXD117zL_3VTo.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.0695,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.3403333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.39066666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.505,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_00"
      }
    ]
  },
  "onwK4e9ZLuTAKqWW03F9::No.": {
    "audioUrl": "/voices/l7uH7ex3AV4W5y8CkH9rlZm0.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.1625,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::What are you thinking about.": {
    "audioUrl": "/voices/khpciQRvu23QkdegkkY3o4Jb.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.05433333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.10866666666666668,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.2205,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3135,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.4256666666666667,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.4683333333333333,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.5536666666666666,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5963333333333334,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.75475,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8245,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.89425,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.964,
        "viseme": "Lips_00"
      }
    ]
  },
  "onwK4e9ZLuTAKqWW03F9::If a hot dog is a sandwich.": {
    "audioUrl": "/voices/U__npT684sUobv4N7uFenwNv.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.0695,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.3016666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.34833333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.5263333333333333,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.6116666666666666,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.697,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.08,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1555,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.231,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.312,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.358,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.4211428571428573,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.4842857142857144,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.6105714285714288,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.673714285714286,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.7368571428571429,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.8,
        "viseme": "Lips_00"
      }
    ]
  },
  "onwK4e9ZLuTAKqWW03F9::I've decided it isn't.": {
    "audioUrl": "/voices/B58NpzMdFJXgY8MN5CkE5R2L.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.1045,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.305,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.378,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.45099999999999996,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.524,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.597,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6699999999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8360000000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.871,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.994,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.059,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.124,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.254,
        "viseme": "Lips_00"
      }
    ]
  }
};
