// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Hi. I'm Lena.": {
    "audioUrl": "/voices/woSCP2aANWOGlMp6svp4yKNh.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.5805,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.842,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.016,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Today: why don't we milk pigs? Stay with me.": {
    "audioUrl": "/voices/zHZMqgHK6liL8ZCWVIykV_E_.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.34800000000000003,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.8765000000000001,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.952,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.01875,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.0505,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.114,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.149,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.1840000000000002,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.219,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.3379999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.399,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.46,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.7065000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.811,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.9155,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.02,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.299,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.380333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.461666666666667,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.589,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.6353333333333335,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.6816666666666666,
        "viseme": "Lips_16"
      },
      {
        "startSec": 2.728,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.8674999999999997,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.96,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Pigs make milk. They have fourteen teats. Cows have four.": {
    "audioUrl": "/voices/ssb5JEdx_a6hzKHy0Y794P_p.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.08125,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.1625,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.24375000000000002,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5343333333333333,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.73125,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8125,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.89375,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.207,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.294,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.439,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.4856666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.5323333333333333,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.579,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.625,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.6985,
        "viseme": "Lips_03"
      },
      {
        "startSec": 1.772,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.8455,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.9189999999999998,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.9924999999999997,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.066,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.136,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.2435,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.351,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.4585,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.566,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.821,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.9370000000000003,
        "viseme": "Lips_09"
      },
      {
        "startSec": 3.053,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.169,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.227,
        "viseme": "Lips_11"
      },
      {
        "startSec": 3.2813333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.3356666666666666,
        "viseme": "Lips_17"
      },
      {
        "startSec": 3.39,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.436,
        "viseme": "Lips_17"
      },
      {
        "startSec": 3.5483333333333333,
        "viseme": "Lips_03"
      },
      {
        "startSec": 3.6606666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 3.773,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::So why isn't pig-milk a thing?": {
    "audioUrl": "/voices/PK081XyHJs7SYFOVtjdXzC80.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.0755,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.27849999999999997,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.4414,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.4878,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5342,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.7313333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7896666666666666,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.9665,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.016,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.0655000000000001,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.173,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.254,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.3506666666666667,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.4473333333333334,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.544,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::The answer is: it doesn't pay.": {
    "audioUrl": "/voices/OeF5_AoQuzwpruUr7tVqnZiu.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.0815,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.29625,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.37150000000000005,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.44675000000000004,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.522,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.871,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.998,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.0619999999999998,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.126,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.173,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2193333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.2656666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.312,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.3583333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.451,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::First: yield.": {
    "audioUrl": "/voices/8_IuTlE4FV1V0PvpVrYfWyG2.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.122,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.366,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.9405,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.05075,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::A cow gives thirty litres a day, for ten months.": {
    "audioUrl": "/voices/xDWRYG4ScN7PTaa0zLN6OEid.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.081,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5690000000000001,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.833,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.923,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.013,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.172,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.2243333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.2766666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.329,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.3813333333333333,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.4336666666666666,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.544,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.579,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.648,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.7759999999999998,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.055,
        "viseme": "Lips_17"
      },
      {
        "startSec": 2.0973333333333333,
        "viseme": "Lips_03"
      },
      {
        "startSec": 2.139666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.182,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.24,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.3213333333333335,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.4026666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.484,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.6351999999999998,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.7163999999999997,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.8788,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.96,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::A sow gives six litres a day, for three weeks.": {
    "audioUrl": "/voices/1UwfX9_b6qjwJQloKh3c_TeI.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.5569999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.82125,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8765000000000001,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.93175,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.068,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.1183333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1686666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.219,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.2693333333333334,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.3196666666666668,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.37,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.451,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.6484999999999999,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.939,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.9853333333333334,
        "viseme": "Lips_03"
      },
      {
        "startSec": 2.0316666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.078,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.136,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.229,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.322,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.415,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.473,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.5774999999999997,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.682,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.7865,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.891,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::And she can't get pregnant while lactating. So each cycle blocks the next litter too.": {
    "audioUrl": "/voices/tA0G5TOXmqdkiTJaYMUR54tC.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.042666666666666665,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.2265,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.42074999999999996,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.4935,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.7313333333333334,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.7776666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.918875,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.96675,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.014625,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.0625,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.110375,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.15825,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.254,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.289,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.347,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.405,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.463,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.498,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.583625,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.66925,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.754875,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.8405,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.9261249999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.01175,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.097375,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.183,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.543,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.6415,
        "viseme": "Lips_08"
      },
      {
        "startSec": 2.74,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.856,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.9665,
        "viseme": "Lips_15"
      },
      {
        "startSec": 3.077,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.135,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.214,
        "viseme": "Lips_02"
      },
      {
        "startSec": 3.2929999999999997,
        "viseme": "Lips_19"
      },
      {
        "startSec": 3.372,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.4509999999999996,
        "viseme": "Lips_13"
      },
      {
        "startSec": 3.53,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.6506,
        "viseme": "Lips_13"
      },
      {
        "startSec": 3.7132,
        "viseme": "Lips_02"
      },
      {
        "startSec": 3.7758,
        "viseme": "Lips_19"
      },
      {
        "startSec": 3.8384,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.901,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.959,
        "viseme": "Lips_16"
      },
      {
        "startSec": 3.9939999999999998,
        "viseme": "Lips_01"
      },
      {
        "startSec": 4.029,
        "viseme": "Lips_20"
      },
      {
        "startSec": 4.11,
        "viseme": "Lips_18"
      },
      {
        "startSec": 4.1658,
        "viseme": "Lips_04"
      },
      {
        "startSec": 4.2216000000000005,
        "viseme": "Lips_19"
      },
      {
        "startSec": 4.2774,
        "viseme": "Lips_14"
      },
      {
        "startSec": 4.333200000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 4.389,
        "viseme": "Lips_20"
      },
      {
        "startSec": 4.435,
        "viseme": "Lips_13"
      },
      {
        "startSec": 4.499,
        "viseme": "Lips_06"
      },
      {
        "startSec": 4.563,
        "viseme": "Lips_18"
      },
      {
        "startSec": 4.627,
        "viseme": "Lips_05"
      },
      {
        "startSec": 4.691,
        "viseme": "Lips_20"
      },
      {
        "startSec": 4.749,
        "viseme": "Lips_18"
      },
      {
        "startSec": 4.9055,
        "viseme": "Lips_07"
      },
      {
        "startSec": 5.062,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Second: speed.": {
    "audioUrl": "/voices/r2ICwi3MbCbICLPjtjVrtJQR.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.09866666666666667,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.19733333333333333,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.296,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.39466666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.94075,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.0685,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.19625,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.324,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Cow milking: ten minutes. Twice a day. Machine does it.": {
    "audioUrl": "/voices/xn8AJIj5EW31G8wUiwyKuuYK.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.122,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.36583333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.42966666666666664,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.4935,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.5573333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6211666666666666,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.8936666666666666,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.9633333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.033,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.139,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.199,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.259,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.319,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.379,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.439,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.497,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.5755000000000001,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.654,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.7325,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.811,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.846,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.869,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.938,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.0545,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.54,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.6189999999999998,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.698,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.7769999999999997,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.856,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.902,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.96,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.0180000000000002,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.076,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.146,
        "viseme": "Lips_06"
      },
      {
        "startSec": 3.227,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.308,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Sow milking: a twenty-second window. Once an hour. After the piglets nuzzle her for two full minutes.": {
    "audioUrl": "/voices/DfW5pSuFkVD8XDbmoobw1sZF.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.145,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.4413333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5226666666666666,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.6853333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7666666666666666,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.114,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.195,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.335,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.393,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.451,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.567,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.625,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.695,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.7471666666666668,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.7993333333333335,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.8515000000000001,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.9036666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.008,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.078,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.15,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.222,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.366,
        "viseme": "Lips_08"
      },
      {
        "startSec": 2.438,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.67,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.7424999999999997,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.815,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.8875,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.96,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.995,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.0300000000000002,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.065,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.134,
        "viseme": "Lips_09"
      },
      {
        "startSec": 3.291,
        "viseme": "Lips_05"
      },
      {
        "startSec": 3.448,
        "viseme": "Lips_20"
      },
      {
        "startSec": 4.005,
        "viseme": "Lips_01"
      },
      {
        "startSec": 4.08325,
        "viseme": "Lips_17"
      },
      {
        "startSec": 4.1615,
        "viseme": "Lips_18"
      },
      {
        "startSec": 4.23975,
        "viseme": "Lips_05"
      },
      {
        "startSec": 4.318,
        "viseme": "Lips_20"
      },
      {
        "startSec": 4.365,
        "viseme": "Lips_16"
      },
      {
        "startSec": 4.4,
        "viseme": "Lips_01"
      },
      {
        "startSec": 4.435,
        "viseme": "Lips_20"
      },
      {
        "startSec": 4.528714285714286,
        "viseme": "Lips_06"
      },
      {
        "startSec": 4.5884285714285715,
        "viseme": "Lips_19"
      },
      {
        "startSec": 4.648142857142857,
        "viseme": "Lips_13"
      },
      {
        "startSec": 4.707857142857143,
        "viseme": "Lips_06"
      },
      {
        "startSec": 4.767571428571428,
        "viseme": "Lips_18"
      },
      {
        "startSec": 4.827285714285714,
        "viseme": "Lips_14"
      },
      {
        "startSec": 4.887,
        "viseme": "Lips_20"
      },
      {
        "startSec": 5.003,
        "viseme": "Lips_18"
      },
      {
        "startSec": 5.0728,
        "viseme": "Lips_01"
      },
      {
        "startSec": 5.1426,
        "viseme": "Lips_14"
      },
      {
        "startSec": 5.212400000000001,
        "viseme": "Lips_01"
      },
      {
        "startSec": 5.2822000000000005,
        "viseme": "Lips_13"
      },
      {
        "startSec": 5.352,
        "viseme": "Lips_20"
      },
      {
        "startSec": 5.41,
        "viseme": "Lips_11"
      },
      {
        "startSec": 5.474,
        "viseme": "Lips_05"
      },
      {
        "startSec": 5.538,
        "viseme": "Lips_20"
      },
      {
        "startSec": 5.619,
        "viseme": "Lips_17"
      },
      {
        "startSec": 5.665333333333333,
        "viseme": "Lips_03"
      },
      {
        "startSec": 5.711666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 5.758,
        "viseme": "Lips_20"
      },
      {
        "startSec": 5.828,
        "viseme": "Lips_18"
      },
      {
        "startSec": 5.955500000000001,
        "viseme": "Lips_07"
      },
      {
        "startSec": 6.083,
        "viseme": "Lips_20"
      },
      {
        "startSec": 6.199,
        "viseme": "Lips_17"
      },
      {
        "startSec": 6.268666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 6.338333333333334,
        "viseme": "Lips_13"
      },
      {
        "startSec": 6.408,
        "viseme": "Lips_20"
      },
      {
        "startSec": 6.5553333333333335,
        "viseme": "Lips_06"
      },
      {
        "startSec": 6.632666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 6.71,
        "viseme": "Lips_01"
      },
      {
        "startSec": 6.787333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 6.8646666666666665,
        "viseme": "Lips_14"
      },
      {
        "startSec": 6.942,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::To trigger oxytocin. You cannot automate that.": {
    "audioUrl": "/voices/Yn7Wn5Avi_G0xAfLLzAUZqee.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.246,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.318,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.39,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.462,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.713,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.811,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.909,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.0070000000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.105,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.203,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.3010000000000002,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.399,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.497,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.579,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.637,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.695,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.764,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.8314,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.8988,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.9662,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.0336,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.101,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.159,
        "viseme": "Lips_03"
      },
      {
        "startSec": 2.2365,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.314,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.3914999999999997,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.5465,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.624,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.658,
        "viseme": "Lips_16"
      },
      {
        "startSec": 2.7666666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.8753333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.984,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Third: the bottom line.": {
    "audioUrl": "/voices/d_48dG7MYYo3yDj_NcOVWy8v.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.14333333333333334,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.2866666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.6735,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8194,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.8728,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.9261999999999999,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9795999999999999,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.091,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.1993333333333334,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.3076666666666665,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.416,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::One sow's entire lactation cycle equals about a week of one cow.": {
    "audioUrl": "/voices/C7datNXzj1lq43ZqNQyoHiZW.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.06566666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.13133333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.3195,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.47050000000000003,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6921999999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.8685999999999999,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.9567999999999999,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.091,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.169375,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.24775,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.326125,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.4045,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.482875,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.56125,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.639625,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.718,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.788,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.8692,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.9504,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.0316,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.1128,
        "viseme": "Lips_13"
      },
      {
        "startSec": 2.194,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.264,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.3354999999999997,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.407,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.4785,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.55,
        "viseme": "Lips_13"
      },
      {
        "startSec": 2.6215,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.693,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.751,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.82075,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.8905,
        "viseme": "Lips_09"
      },
      {
        "startSec": 2.96025,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.03,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.088,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.123,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.216,
        "viseme": "Lips_07"
      },
      {
        "startSec": 3.312666666666667,
        "viseme": "Lips_06"
      },
      {
        "startSec": 3.409333333333333,
        "viseme": "Lips_19"
      },
      {
        "startSec": 3.506,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.587,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.6335,
        "viseme": "Lips_17"
      },
      {
        "startSec": 3.68,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.808,
        "viseme": "Lips_07"
      },
      {
        "startSec": 3.893,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.9779999999999998,
        "viseme": "Lips_18"
      },
      {
        "startSec": 4.063,
        "viseme": "Lips_20"
      },
      {
        "startSec": 4.121,
        "viseme": "Lips_19"
      },
      {
        "startSec": 4.307,
        "viseme": "Lips_09"
      },
      {
        "startSec": 4.493,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::A Dutch farmer named Erik Stegink tried anyway.": {
    "audioUrl": "/voices/fdroZnzzD7DJzM6Lfk6h2YFC.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.21666666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.29433333333333334,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.495,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.56,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.625,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.69,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.87375,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.99525,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.056,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.2335,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.306,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.3785,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.451,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.544,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.6235714285714287,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.703142857142857,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.7827142857142857,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.8622857142857143,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.9418571428571427,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.0214285714285714,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.101,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.159,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.2432499999999997,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.3274999999999997,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.41175,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.496,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.542,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.6304,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.7188,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.8072,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.8956,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::His pig-milk cheese took forty hours per batch.": {
    "audioUrl": "/voices/JkYmPskvC5Gf4CztdM6_JwVC.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.057999999999999996,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.11599999999999999,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.298,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.35200000000000004,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5225,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.6155,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.828,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.925,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.057,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.1226666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.1883333333333332,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.254,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.324,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.3866,
        "viseme": "Lips_03"
      },
      {
        "startSec": 1.4492,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.5118,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.5744,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.637,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.695,
        "viseme": "Lips_09"
      },
      {
        "startSec": 1.7803333333333333,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.8656666666666668,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.951,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.09,
        "viseme": "Lips_05"
      },
      {
        "startSec": 2.171,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.365,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.489,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.613,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::So: we don't milk pigs because the math doesn't work.": {
    "audioUrl": "/voices/zkqiCaFJ_a5yjkUx0ZeGBIIS.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.145,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.424,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.58625,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.6385000000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8502500000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8995,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.94875,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.998,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.14925,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.2305000000000001,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.31175,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.393,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.5090000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.5670000000000002,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.625,
        "viseme": "Lips_03"
      },
      {
        "startSec": 1.683,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.741,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.776,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.811,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.846,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.9963333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.0776666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.159,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.217,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.2635,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.31,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.3565,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.403,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.496,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.542,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.666,
        "viseme": "Lips_05"
      },
      {
        "startSec": 2.79,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.914,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::The pigs win.": {
    "audioUrl": "/voices/lSW6R_m2yO0esbQMOYDaEhKN.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.0695,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.26425,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3425,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.42075,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.631,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7160000000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::...so. That's why. See you next time.": {
    "audioUrl": "/voices/OYPwhKpWS0HU1aUIZfaZbSUq.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.104,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.22599999999999998,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.479,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.54,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.601,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.8474999999999999,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.173,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.2774999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.382,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.405,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.44,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.475,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.5628,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.6046,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.6463999999999999,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.6882,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.73,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.753,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.8536666666666666,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.9543333333333335,
        "viseme": "Lips_20"
      }
    ]
  }
};
