// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Hi. I'm Lena.": {
    "audioUrl": "/voices/woSCP2aANWOGlMp6svp4yKNh.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.5805,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.842,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.016,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Today: why two percent of mobile game players.": {
    "audioUrl": "/voices/dL4xq4i6toEgR25uKMXR6nPt.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.119,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.238,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.357,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.9635,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.114,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.288,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.404,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.52,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.59,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.6558333333333335,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.7216666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.7875,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.8533333333333335,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.985,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.055,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.0955000000000004,
        "viseme": "Lips_17"
      },
      {
        "startSec": 2.136,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.205,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.2864,
        "viseme": "Lips_08"
      },
      {
        "startSec": 2.3678,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.4492000000000003,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.5306,
        "viseme": "Lips_13"
      },
      {
        "startSec": 2.612,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.67,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.743333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.816666666666667,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.89,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.914,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.9928,
        "viseme": "Lips_13"
      },
      {
        "startSec": 3.0716,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.1504,
        "viseme": "Lips_05"
      },
      {
        "startSec": 3.2292,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.308,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Make fifty percent of the revenue.": {
    "audioUrl": "/voices/F5zx4sKGMOJu74bPxUZK8Jue.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.08133333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.16266666666666665,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.3646,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.4272,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.4898,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.5524,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.737,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.865,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.057,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.091,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.126,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.208,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.2425,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.324,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.411,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.498,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.585,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.6720000000000002,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.7590000000000001,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.846,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Stay with me.": {
    "audioUrl": "/voices/C5Q9c9xcieag8XJrxe6lEQq0.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.10433333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.20866666666666667,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.48800000000000004,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.6905,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Free-to-play mobile games.": {
    "audioUrl": "/voices/sEa_FzEK948AvANvq8N1tJzP.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.08133333333333333,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.16266666666666665,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.32499999999999996,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.468,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.53,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.7386,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.8151999999999999,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8917999999999999,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9683999999999999,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.19875,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.2945,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.39025,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Less than two percent of players ever pay.": {
    "audioUrl": "/voices/1KufBewkqIRhKdxC0M1UpjZA.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.06966666666666667,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.13933333333333334,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.2866666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.3293333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.48750000000000004,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.675,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.735,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.7949999999999999,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.855,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.0390000000000001,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.068,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.114,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.1838000000000002,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.2536,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.3234000000000001,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.3932000000000002,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.463,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.579,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.6796666666666666,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.7803333333333333,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.881,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.95,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.1125,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Those two percent fund the whole industry.": {
    "audioUrl": "/voices/vn9rRLA_92tLQspAIBu_wyRT.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.09666666666666666,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.19333333333333333,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.3945,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.522,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5860000000000001,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.65,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.714,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.906,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.964,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.08,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.242,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.2825,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.323,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.37,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.4356666666666666,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.5013333333333334,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.567,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.614,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.677875,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.805625,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.8695,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.933375,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.99725,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.061125,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.125,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::The store is the weapon.": {
    "audioUrl": "/voices/qcYm58vVayrVxieetDvQOXHL.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.0755,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.29025,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.37150000000000005,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.45275000000000004,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6965,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.8999999999999999,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.952,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.1124,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.2028,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.2932000000000001,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.3836,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Let's start with the red dot.": {
    "audioUrl": "/voices/0YBuuj6uP94REWTa1JfpNeP3.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.061,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.122,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.183,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.3276,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.37620000000000003,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.4248,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.47340000000000004,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.522,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.6116666666666666,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6543333333333333,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.697,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.9440000000000001,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.006,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.068,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.138,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2616666666666665,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.3853333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.509,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::You know the one. On the shop icon.": {
    "audioUrl": "/voices/1crx6grJ_k2nQ_gunU6rG9y6.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.0815,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.2905,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.4585,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.6306666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7043333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.051,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.1960000000000002,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.231,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.3466666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.4163333333333332,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.602,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.7007500000000002,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.7995,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.89825,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.997,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::A 2024 study looked at fourteen hundred games.": {
    "audioUrl": "/voices/OX9Y8BaJiZbCpcamvF43cOHL.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.114,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.1768,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2396,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.3024,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.3652,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.497,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.558,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.6190000000000002,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.6800000000000002,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.741,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.788,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.8399999999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.892,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.962,
        "viseme": "Lips_17"
      },
      {
        "startSec": 2.0375,
        "viseme": "Lips_03"
      },
      {
        "startSec": 2.113,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.1885,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.2640000000000002,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.3395,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.415,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.507,
        "viseme": "Lips_11"
      },
      {
        "startSec": 2.5684285714285715,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.629857142857143,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.7527142857142857,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.814142857142857,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.8755714285714284,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.937,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.018,
        "viseme": "Lips_19"
      },
      {
        "startSec": 3.1487499999999997,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.2794999999999996,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.41025,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.541,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::It has a name. Visual Prominence.": {
    "audioUrl": "/voices/NNh5ZKeBnrIQNBwXBm6FCuVJ.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.064,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.23233333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.2786666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.6193333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.7506666666666666,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.068,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.121,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1740000000000002,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.227,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.28,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.3330000000000002,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.3860000000000001,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.439,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.509,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.5773333333333333,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.6456666666666666,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.714,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.7823333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.8506666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.919,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.9873333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.0556666666666668,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.124,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::The dot is engineered.": {
    "audioUrl": "/voices/NpRKVYvkhPOsRM2oW28Qf1ml.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.0815,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.2906666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.36033333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.65,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.729875,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.80975,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.889625,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9695,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.049375,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1292499999999999,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.2091249999999998,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.289,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::It does not mean you have something to claim.": {
    "audioUrl": "/voices/FoO4176THGwOOULpTVhDMXK7.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.20933333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.25566666666666665,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.39466666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.4413333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5843333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6346666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.9283333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9746666666666666,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.021,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.056,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.114,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.172,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.23,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.288,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.3459999999999999,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.404,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.451,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.602,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.7035,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.8050000000000002,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.9065,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.008,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::It means: open the shop.": {
    "audioUrl": "/voices/9hRic3JMC1AeOlfygmrsqsLT.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.0695,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.25275000000000003,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3195,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.38625,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.7370000000000001,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.865,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.057,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.2153333333333334,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.3276666666666666,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.44,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Now. The three bundles.": {
    "audioUrl": "/voices/9v7pPD5haKOf08tU4cZquu8G.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.1395,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.48750000000000004,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.6963333333333334,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.7776666666666666,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.99,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.063,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.209,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.282,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.355,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Four ninety-nine. Nineteen ninety-nine. Forty-nine ninety-nine.": {
    "audioUrl": "/voices/Pjg7K0O4y79ZVKOR4bShtarQ.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.07366666666666667,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.14733333333333334,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.3346,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.39020000000000005,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.5014000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.7156666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.8163333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.289,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.3663333333333332,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.4436666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.5983333333333332,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.6756666666666664,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.753,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.823,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.8834,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.9438,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.0646,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.125,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.183,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.2876666666666665,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.392333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.497,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.578,
        "viseme": "Lips_17"
      },
      {
        "startSec": 2.643,
        "viseme": "Lips_03"
      },
      {
        "startSec": 2.7079999999999997,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.773,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.838,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.903,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.961,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.038333333333333,
        "viseme": "Lips_02"
      },
      {
        "startSec": 3.115666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.193,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.251,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.316,
        "viseme": "Lips_02"
      },
      {
        "startSec": 3.381,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.511,
        "viseme": "Lips_06"
      },
      {
        "startSec": 3.576,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.634,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.754,
        "viseme": "Lips_02"
      },
      {
        "startSec": 3.874,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.994,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::This is the Decoy Effect.": {
    "audioUrl": "/voices/EfTPFxSoNY4HsbEcX_Y2BGS9.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.07733333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.15466666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3655,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.7925,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.923,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.0535,
        "viseme": "Lips_10"
      },
      {
        "startSec": 1.184,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.3,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.4116,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.5232,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.6348,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.7464,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.858,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Marketing researchers proved it in 1981.": {
    "audioUrl": "/voices/WT_92ZR2mheeQ06IzdUYbjz9.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.0595,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.119,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.1785,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.238,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.2975,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.357,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.4165,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.522,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.6067142857142858,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6914285714285715,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.7761428571428571,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.8608571428571429,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.9455714285714286,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.0302857142857142,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.261,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.3259999999999998,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.391,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.456,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.568,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.6085,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.649,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.707,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.7475,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.788,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::The middle one exists to sell the top one.": {
    "audioUrl": "/voices/oRqpqKrQOT1jPXdnb8ZPkKXQ.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.064,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.2348,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.28359999999999996,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.3324,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.3812,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.5186666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5613333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.65,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7031428571428572,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.7562857142857143,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.8094285714285714,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8625714285714285,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.9157142857142857,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.9688571428571429,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.057,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.0915,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.126,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.2656666666666667,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.3353333333333333,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.405,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.463,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.498,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.533,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.579,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.6526666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.7263333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.8,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.881,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.9583333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.0356666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.113,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::You're not picking a bundle.": {
    "audioUrl": "/voices/YmQPrku3vWzl6nxHSMLtnb_p.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.08900000000000001,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.17800000000000002,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.33266666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.3753333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5222,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5804,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.6386000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6968,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.9733333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.0526666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2113333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.2906666666666669,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.37,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::You're picking a middle.": {
    "audioUrl": "/voices/4_XnijD9ZYMK8r0okKMuHVxC.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.09300000000000001,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.18600000000000003,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.40900000000000003,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.481,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.5529999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.625,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.697,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.836,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.9984000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.0798,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.1612,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.2426,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.324,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::Last one. Your friends.": {
    "audioUrl": "/voices/dmIZNCntVI2gg959wYzA3Z_4.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.0755,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.22649999999999998,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.457,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.542,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8126666666666666,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.8823333333333333,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.952,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.0973333333333333,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.1726666666666667,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.248,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.3986666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::When a friend buys a skin.": {
    "audioUrl": "/voices/K4BEm_S1BbsIO4ylmH3s1Mcx.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.07366666666666667,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.14733333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.4346,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.49720000000000003,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.5598000000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8666666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.9673333333333334,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.068,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.149,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.219,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.265,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.3695,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.5785,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.683,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::The notification routes to the shop page.": {
    "audioUrl": "/voices/zV8EuXi4e6_Eh8SAzzSyfnd5.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.064,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.24927272727272726,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.31254545454545457,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.37581818181818183,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.4390909090909091,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.5023636363636363,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5656363636363637,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.6289090909090909,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.6921818181818182,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.7554545454545454,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.8187272727272727,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.952,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.02175,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.0915,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.1612500000000001,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.231,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.289,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.3239999999999998,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.359,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.417,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.4515,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.533,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.6063333333333332,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.6796666666666666,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.753,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.811,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.9466666666666665,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.082333333333333,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.218,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::It has a name too. Parasocial Pressure.": {
    "audioUrl": "/voices/rUWbM7kZa4d_YVhzsM7q4Yvm.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.0695,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.24366666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.29033333333333333,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.65,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.923,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.08,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.614,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.6988,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.7836,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.8684000000000003,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.9532000000000003,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.0380000000000003,
        "viseme": "Lips_08"
      },
      {
        "startSec": 2.1228000000000002,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.2076000000000002,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.2924,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.3772,
        "viseme": "Lips_13"
      },
      {
        "startSec": 2.462,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.554,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.6632,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.7723999999999998,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.8815999999999997,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.9908,
        "viseme": "Lips_05"
      },
      {
        "startSec": 3.1,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::They are using your social bonds.": {
    "audioUrl": "/voices/bsSgAPpE11T7Sbya3pBj3RJR.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.093,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.4738,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.5296,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.5853999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6412,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.697,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8053333333333333,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.8556666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.906,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.964,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.0406,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.1172,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.1938,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.2704,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.347,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.5164,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.6048,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.7816,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.87,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::These are not accidents.": {
    "audioUrl": "/voices/ud9Fk5cmnDVSywt4oaZZPhG_.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.08133333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.16266666666666665,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.3255,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7328888888888889,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.8037777777777778,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.8746666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9455555555555556,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.0164444444444445,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.0873333333333335,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.229111111111111,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.3,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::This is decades of behavioral research. Weaponized.": {
    "audioUrl": "/voices/zsKit0IhPjHNxlD4V_HWJbLA.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.08900000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.17800000000000002,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.7793333333333333,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.8856666666666667,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.992,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.0983333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2046666666666668,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.311,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.358,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.393,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.5517777777777777,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.6175555555555556,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.6833333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.749111111111111,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.8148888888888888,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.8806666666666665,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.9464444444444444,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.0122222222222224,
        "viseme": "Lips_13"
      },
      {
        "startSec": 2.078,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.136,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.245,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.354,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.463,
        "viseme": "Lips_05"
      },
      {
        "startSec": 2.572,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.681,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.041,
        "viseme": "Lips_07"
      },
      {
        "startSec": 3.12,
        "viseme": "Lips_04"
      },
      {
        "startSec": 3.199,
        "viseme": "Lips_02"
      },
      {
        "startSec": 3.278,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.3569999999999998,
        "viseme": "Lips_08"
      },
      {
        "startSec": 3.436,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.5149999999999997,
        "viseme": "Lips_06"
      },
      {
        "startSec": 3.594,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.673,
        "viseme": "Lips_04"
      },
      {
        "startSec": 3.752,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.831,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::And you opened the app.": {
    "audioUrl": "/voices/NryowVG1MYL4ZRCSXrbk1nBD.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.057999999999999996,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.2785,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.4434,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5038,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5642,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.7665,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.0215,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.149,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::...so. That's why.": {
    "audioUrl": "/voices/GuRxMruNh9G_uIQGtv86ODPy.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.47925,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5285,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.57775,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.7955000000000001,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_20"
      }
    ]
  },
  "Xb7hH8MSUJpSbSDYk0k2::eleven_flash_v2_5::See you next time.": {
    "audioUrl": "/voices/U0d7mT9lXKCcH7hN_qXg5QST.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.093,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.381,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.42500000000000004,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.46900000000000003,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.513,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.6806666666666666,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.7813333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_20"
      }
    ]
  }
};
