// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "JBFqnCBsd6RMkjVDRZzb::eleven_flash_v2_5::He is the last who remembers it.": {
    "audioUrl": "/voices/antSCiEuyvHXEk6poIlIf8M6.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.2205,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.5025,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.575,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.6475,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.7955,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.967875,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.01875,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.069625,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.1205,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.22225,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.273125,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.324,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.382,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.4514999999999998,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_00"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::eleven_flash_v2_5::The song is older than he is.": {
    "audioUrl": "/voices/hgTxkUH2GBtSaHKRoO45we3R.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.064,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.25933333333333336,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.33266666666666667,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5165,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.6619999999999999,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.836,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.871,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.9133333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9556666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.998,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.0915,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.138,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.219,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.3235000000000001,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_00"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::eleven_flash_v2_5::Some things only pass by ear.": {
    "audioUrl": "/voices/wbTtzazsL_LNhtyW_3lFAx5o.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.085,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.17,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.35974999999999996,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.4295,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.49924999999999997,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.65,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.8240000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.952,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.0333333333333332,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.1146666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.254,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.341,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.666,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.811,
        "viseme": "Lips_00"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::eleven_flash_v2_5::She knows it too.": {
    "audioUrl": "/voices/pCFP2_J2P9z5tvVhcCL7E9sE.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.0755,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.27466666666666667,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.3403333333333334,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.505,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.7255,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_00"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::eleven_flash_v2_5::And the song goes on.": {
    "audioUrl": "/voices/gU_nO0UU3Uzv6dA4Q6NxaU7Q.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.06966666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.29600000000000004,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.4643333333333333,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.5456666666666666,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.7506666666666667,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.8163333333333334,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.94,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.0565,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.173,
        "viseme": "Lips_00"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::eleven_flash_v2_5::Some songs only end when we stop singing them.": {
    "audioUrl": "/voices/0f5EmrCiZOzLXQA_OLv6xZET.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.085,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.17,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.38325,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.4645,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.54575,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.78375,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.8474999999999999,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.91125,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.056,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.1296666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.335,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.3853333333333333,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.4356666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.5554999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.59,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.648,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.7062499999999998,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.7645,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.82275,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.881,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.95,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.0058,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.0616,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.1174,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.1732,
        "viseme": "Lips_19"
      },
      {
        "startSec": 2.229,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.275,
        "viseme": "Lips_16"
      },
      {
        "startSec": 2.3293333333333335,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.3836666666666666,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.438,
        "viseme": "Lips_00"
      }
    ]
  }
};
