// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "JBFqnCBsd6RMkjVDRZzb::He is the last who remembers it.": {
    "audioUrl": "/voices/WvT5GJ7fUrfd0IUqRPX8kG7F.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.07,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.94,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 1.207,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.254,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 1.335,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.405,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 1.463,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.532,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.567,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.683,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::The song is older than he is.": {
    "audioUrl": "/voices/ld5MD1PGPiWH0_7RuG_4msbR.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.104,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.522,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 0.697,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.906,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.94,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.022,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 1.068,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.115,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.184,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 1.393,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::Some things only pass by ear.": {
    "audioUrl": "/voices/QgkDe6oSg5jOyOmDkVwaWRAJ.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.081,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.952,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.091,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 1.219,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 1.335,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.672,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 1.718,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.834,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::She knows it too.": {
    "audioUrl": "/voices/_eLb6CHIdqY98bTjxVnX63hG.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.081,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::And the song goes on.": {
    "audioUrl": "/voices/oW5_JMQJVfv0w5eg_jVi_Xmo.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.104,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.033,
        "viseme": "Lips_s00_Default"
      }
    ]
  },
  "JBFqnCBsd6RMkjVDRZzb::Some songs only end when we stop singing them.": {
    "audioUrl": "/voices/vo2smlsPwwwpPMcHGJfbVtTv.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.093,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 0.906,
        "viseme": "Lips_s09_L"
      },
      {
        "startSec": 0.964,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 0.998,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.068,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.219,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.253,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.311,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 1.346,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 1.381,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.439,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_s11_o-u-w"
      },
      {
        "startSec": 1.509,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 1.555,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.602,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 1.648,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 1.706,
        "viseme": "Lips_s10_oh"
      },
      {
        "startSec": 1.776,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 1.846,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 1.904,
        "viseme": "Lips_s06_s-z"
      },
      {
        "startSec": 1.95,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 2.008,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.089,
        "viseme": "Lips_s02_a-i"
      },
      {
        "startSec": 2.136,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.194,
        "viseme": "Lips_s00_Default"
      },
      {
        "startSec": 2.24,
        "viseme": "Lips_s04_th"
      },
      {
        "startSec": 2.263,
        "viseme": "Lips_s03_ah-i"
      },
      {
        "startSec": 2.287,
        "viseme": "Lips_s05_e-k-r"
      },
      {
        "startSec": 2.322,
        "viseme": "Lips_s07_m-b-p"
      },
      {
        "startSec": 2.403,
        "viseme": "Lips_s00_Default"
      }
    ]
  }
};
