// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "cjVigY5qzO86Huf0OWal::eleven_flash_v2_5::Hey. Can I ask you something?": {
    "audioUrl": "/voices/LKLhkTjbu8BbynGXQZt2fQ8P.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.093,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.27066666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.30933333333333335,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5263333333333333,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.5766666666666667,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6965,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.8321666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.8863333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.9405,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.9946666666666667,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.0488333333333333,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::Mhm?": {
    "audioUrl": "/voices/ffMvjLPdOCROBfICmijKV7jU.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.079,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.158,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.237,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.316,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_00"
      }
    ]
  },
  "cjVigY5qzO86Huf0OWal::eleven_flash_v2_5::Does your dad actually have cancer?": {
    "audioUrl": "/voices/mXtqU4VDLfTd5z7a_6GxJR5_.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.050333333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.10066666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.205,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.23600000000000002,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.375,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.437,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5857142857142857,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.6254285714285714,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.6651428571428571,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.7048571428571428,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7445714285714286,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.7842857142857143,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.8976666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9363333333333334,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.975,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.0866,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.1632,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2398,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.3164,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.393,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::No.": {
    "audioUrl": "/voices/j3MEJmnayawgklS2LkoB45wR.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::No no!": {
    "audioUrl": "/voices/a2J5m6QKFpCjTgfp6d4O6SoI.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.4355,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::Don't do this.": {
    "audioUrl": "/voices/2HSZmqLVRg_TKkZ_PY9OtJxl.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.04925,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.0985,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.27849999999999997,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.4453333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5186666666666666,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::No no no no no!": {
    "audioUrl": "/voices/317Njp90Sy5W0V_iTbx3JjhH.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.0815,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.2555,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.5225,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::Why are you asking me this?": {
    "audioUrl": "/voices/0SmDMpVSA7st5NSiegwrZQQU.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.0815,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.273,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5317999999999999,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.5876,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.6434,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6992,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8415,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.006,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.095,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.184,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::NO NO NO NO NO!": {
    "audioUrl": "/voices/O8k96djUh23D3NV52tNTOzCY.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.0755,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.4065,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.7375,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::I thought we were having a nice night.": {
    "audioUrl": "/voices/XRQ0DnbF4_X8mMLwquKJdxE1.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.182,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.236,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.3425,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.47000000000000003,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.534,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.6132,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.6574,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.7016,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7458,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.79,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.825,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.9636666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.0333333333333332,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2463333333333333,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.3316666666666668,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.417,
        "viseme": "Lips_00"
      }
    ]
  },
  "cjVigY5qzO86Huf0OWal::eleven_flash_v2_5::Okay.": {
    "audioUrl": "/voices/8sDtY7aIgS_il2WFhf9rPpap.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.16633333333333333,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.33266666666666667,
        "viseme": "Lips_00"
      }
    ]
  },
  "cjVigY5qzO86Huf0OWal::eleven_flash_v2_5::I won't ask again. I'm sorry.": {
    "audioUrl": "/voices/8M_n4_dB3d89hhZ4rvz5eemx.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.058,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.116,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.1595,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.203,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5952500000000001,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.6445000000000001,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.69375,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.8415,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.952,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.0245,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.097,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.1695,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.242,
        "viseme": "Lips_00"
      }
    ]
  },
  "cgSgspJ2msm6clMCkdW9::eleven_flash_v2_5::So! How's your pasta?": {
    "audioUrl": "/voices/S3nQ9NQLMwTu5Dq8eQ8JHaIT.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.1275,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.48800000000000004,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.611,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.642,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.7916,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.8752,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.9587999999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.0423999999999998,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.126,
        "viseme": "Lips_00"
      }
    ]
  }
};
