// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Good evening!": {
    "audioUrl": "/voices/l15tG7JHcOBG5hHg7g4mY1lC.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.06566666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.13133333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.309,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.374,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.43899999999999995,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.504,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::My name is Marcus — and I don't exist!": {
    "audioUrl": "/voices/BwHTYomyDVawEr4ipk3ylo5L.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.064,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.128,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.21666666666666665,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.2593333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.366,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5436666666666666,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.6113333333333333,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.679,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.7466666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.8143333333333334,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.254,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.3006666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.394,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.44,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.463,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.51,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.54775,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.5855000000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.661,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.695,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.7531666666666668,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.8113333333333335,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.8695,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.9276666666666666,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.9858333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.044,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::I was rendered, this morning, in twenty minutes.": {
    "audioUrl": "/voices/xuuApLZVJeVa5XhKKTNy3wX1.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.07,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.17766666666666667,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.21633333333333332,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.39649999999999996,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.445,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.542,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.5905,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.7276666666666667,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7703333333333333,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.929,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.9793333333333334,
        "viseme": "Lips_03"
      },
      {
        "startSec": 1.0296666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.08,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.1303333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1806666666666668,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.231,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.335,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.399,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.463,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.5675,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.6139999999999999,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.6604999999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.7535,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.8,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.846,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.8963333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.9466666666666668,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.997,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.0473333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.097666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.148,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::And I would love to show you how.": {
    "audioUrl": "/voices/iWHUXGv3k2K1RdxcBIHOXk8W.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.04633333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.27466666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.31733333333333336,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.4683333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5186666666666666,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.633,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.83,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.94,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.062,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.114,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.23,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.3635000000000002,
        "viseme": "Lips_09"
      },
      {
        "startSec": 1.497,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Start with me.": {
    "audioUrl": "/voices/qZFoWa2Yin096LAdLOHNx2aD.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.0534,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.1068,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.1602,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.2136,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.34833333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.39466666666666667,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.441,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5865,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::I am one rig — fifty-three bones — shared across every outfit.": {
    "audioUrl": "/voices/PRFiGw8LqHsFe9xFWk95Wcd4.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.07,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.1915,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.387,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.449,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.6343333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7116666666666667,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.2631999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.3304,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.3976,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.4647999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.532,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.579,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.6446666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.7103333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.776,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.823,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.91,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.9969999999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.0839999999999996,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.171,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.67,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.7455,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.8209999999999997,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.8965,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.972,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.995,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.0554,
        "viseme": "Lips_19"
      },
      {
        "startSec": 3.1158,
        "viseme": "Lips_12"
      },
      {
        "startSec": 3.1762,
        "viseme": "Lips_03"
      },
      {
        "startSec": 3.2366,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.297,
        "viseme": "Lips_00"
      },
      {
        "startSec": 3.39,
        "viseme": "Lips_04"
      },
      {
        "startSec": 3.451,
        "viseme": "Lips_17"
      },
      {
        "startSec": 3.512,
        "viseme": "Lips_05"
      },
      {
        "startSec": 3.573,
        "viseme": "Lips_06"
      },
      {
        "startSec": 3.634,
        "viseme": "Lips_00"
      },
      {
        "startSec": 3.692,
        "viseme": "Lips_09"
      },
      {
        "startSec": 3.7640000000000002,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.836,
        "viseme": "Lips_17"
      },
      {
        "startSec": 3.908,
        "viseme": "Lips_06"
      },
      {
        "startSec": 3.9799999999999995,
        "viseme": "Lips_18"
      },
      {
        "startSec": 4.052,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Hair, glasses, shirt, trousers — three hundred combinations.": {
    "audioUrl": "/voices/d79s6W0lAS086VfZ3GBE2Qdo.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.09666666666666666,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.19333333333333333,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.5808333333333333,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.6736666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7665,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.8593333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9521666666666666,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.185,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.3086666666666666,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.4323333333333335,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.556,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.719,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.8195000000000001,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.9200000000000002,
        "viseme": "Lips_09"
      },
      {
        "startSec": 2.0205,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.121,
        "viseme": "Lips_05"
      },
      {
        "startSec": 2.2215,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.322,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.752,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.8256666666666663,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.8993333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.973,
        "viseme": "Lips_00"
      },
      {
        "startSec": 3.007,
        "viseme": "Lips_11"
      },
      {
        "startSec": 3.0385714285714287,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.0701428571428573,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.1332857142857145,
        "viseme": "Lips_12"
      },
      {
        "startSec": 3.164857142857143,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.1964285714285716,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.228,
        "viseme": "Lips_00"
      },
      {
        "startSec": 3.274,
        "viseme": "Lips_19"
      },
      {
        "startSec": 3.331,
        "viseme": "Lips_02"
      },
      {
        "startSec": 3.388,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.502,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.559,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.6159999999999997,
        "viseme": "Lips_00"
      },
      {
        "startSec": 3.673,
        "viseme": "Lips_15"
      },
      {
        "startSec": 3.73,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.787,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.844,
        "viseme": "Lips_14"
      },
      {
        "startSec": 3.901,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Swap any of it, and the animation still fits.": {
    "audioUrl": "/voices/Qf6GQHPf30yxUxajXseiUdgi.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.09575,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.1915,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.28725,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.476,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.5456666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.6153333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.685,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.778,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.859,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.923,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.231,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.2813333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.382,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.417,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.4515,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.521,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.5747499999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.6284999999999998,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.68225,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.736,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.78975,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.8435000000000001,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.89725,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.951,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.997,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.0492500000000002,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.1015,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.15375,
        "viseme": "Lips_13"
      },
      {
        "startSec": 2.206,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.264,
        "viseme": "Lips_17"
      },
      {
        "startSec": 2.3425,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.421,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.4995,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.578,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Speaking of which —": {
    "audioUrl": "/voices/Xwu6sBBmAfjLbMJp2bAkV4HX.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.06966666666666667,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.13933333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.20900000000000002,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.2786666666666667,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.34833333333333333,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.48750000000000004,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.557,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.6343333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7116666666666667,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::seventeen motion clips drive everything I do.": {
    "audioUrl": "/voices/McveRVbVfPQnYYUafeHYBTYm.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.0725,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.145,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.21749999999999997,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.43499999999999994,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5075,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.7224,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.7828,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.8432,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9036,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.964,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.01,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.061,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.1119999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1629999999999998,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.214,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.265,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.3,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.364,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.428,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.492,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.556,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.602,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.6434285714285715,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.6848571428571428,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.7262857142857144,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.7677142857142858,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.8091428571428572,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.8505714285714285,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.892,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.962,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.985,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.067,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.154,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.241,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Discussion. Thinking. Yes. Thumbs up.": {
    "audioUrl": "/voices/skO5_i_dPX9C_D394sO_za_z.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.09,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.18,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.27,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.44999999999999996,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.54,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.63,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.1281666666666665,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.2113333333333334,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.3776666666666666,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.4608333333333334,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.544,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.869,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.9966666666666666,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.1243333333333334,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.252,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.345,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.42925,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.5135,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.59775,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.682,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.751,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.8265000000000002,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.902,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::All composed on a timeline — to the frame.": {
    "audioUrl": "/voices/UHM6nsiFiMWX9zIVu1IQi8CR.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.0985,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.33,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.393,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.5189999999999999,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.582,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.6449999999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.772,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.801,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.94,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.031,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.1219999999999999,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.213,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.304,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.395,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.578,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.6480000000000001,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.718,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.787,
        "viseme": "Lips_16"
      },
      {
        "startSec": 1.822,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.857,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.904,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.9909999999999999,
        "viseme": "Lips_12"
      },
      {
        "startSec": 2.078,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.165,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.252,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Now look at the camera.": {
    "audioUrl": "/voices/a7UqTiwu1ccmNUw5zEX_ecB4.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.087,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.3056666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.37933333333333336,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.569,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.6445,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.8355,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.917,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.996,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.075,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.154,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.233,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.312,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::It is never still.": {
    "audioUrl": "/voices/vRAWCuM_EexZPClb88E9Zvf4.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.052,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.104,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.221,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.302,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.357,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.41200000000000003,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.467,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.522,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.6555,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8065,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.882,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Wide!": {
    "audioUrl": "/voices/BKbJszLibCah7s2TxNBMLvuz.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.16266666666666665,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.3253333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.488,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Close!": {
    "audioUrl": "/voices/0pUZPktkuEvXBh9rysWawvEd.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.12475,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.2495,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.37424999999999997,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Profile!": {
    "audioUrl": "/voices/IeZ_Ky_TnnZ7ZesuztkVvpU_.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.1025,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.205,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.3075,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.41,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.5125,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Bird's eye. Worm's eye. Dutch tilt.": {
    "audioUrl": "/voices/WcUbhgxcN3byrfunPGvklknY.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.09,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.18,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.27,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.964,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.0655000000000001,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.167,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.2685,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.37,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.44,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.707,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.962,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.059,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.156,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.253,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.288,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.36925,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.4505,
        "viseme": "Lips_13"
      },
      {
        "startSec": 2.5317499999999997,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.613,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Field of view, position, roll — all tween independently.": {
    "audioUrl": "/voices/8xxxcny8EcveCsmTePe_8Aqg.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.087,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.261,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.538,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.623,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.836,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.9138571428571428,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.9917142857142857,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.0695714285714286,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1474285714285715,
        "viseme": "Lips_15"
      },
      {
        "startSec": 1.2252857142857143,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.3031428571428572,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.381,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.509,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.6173333333333333,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.7256666666666667,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.834,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.008,
        "viseme": "Lips_03"
      },
      {
        "startSec": 2.1125,
        "viseme": "Lips_13"
      },
      {
        "startSec": 2.217,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.275,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.34475,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.4145,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.48425,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.554,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.612,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.6566923076923077,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.7460769230769233,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.790769230769231,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.8354615384615385,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.880153846153846,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.9695384615384617,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.0142307692307693,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.103615384615385,
        "viseme": "Lips_13"
      },
      {
        "startSec": 3.1483076923076925,
        "viseme": "Lips_06"
      },
      {
        "startSec": 3.193,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Every shot was chosen — for you.": {
    "audioUrl": "/voices/An3xeoPtCkdRnuwsP_HKRDSh.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.06675,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.1335,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.20025,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.325,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.41,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.495,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.6616666666666666,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.6963333333333334,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.731,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.8726,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.9562,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.0398,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.1234000000000002,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.207,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.602,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.6443333333333334,
        "viseme": "Lips_03"
      },
      {
        "startSec": 1.6866666666666668,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.729,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.787,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.8624999999999998,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.938,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::And this voice?": {
    "audioUrl": "/voices/DaXYPIcp0nmwmPdqYjoiFk4g.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.04633333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.22833333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.27066666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.46066666666666667,
        "viseme": "Lips_10"
      },
      {
        "startSec": 0.5613333333333334,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.662,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Synthesized. Aligned to my mouth by phoneme.": {
    "audioUrl": "/voices/9qPgJhSulVKoIIZTPgbyPVf4.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.08388888888888889,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.16777777777777778,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.33555555555555555,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.41944444444444445,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.5033333333333333,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.5872222222222222,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.6711111111111111,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.092,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.1894,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.2868,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.3841999999999999,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.579,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.626,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.6549999999999998,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.684,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.753,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.7995,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.846,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.939,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.0163333333333333,
        "viseme": "Lips_09"
      },
      {
        "startSec": 2.0936666666666666,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.171,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.229,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.2815000000000003,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.334,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.392,
        "viseme": "Lips_17"
      },
      {
        "startSec": 2.4661999999999997,
        "viseme": "Lips_08"
      },
      {
        "startSec": 2.5404,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.6146,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.6888,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.763,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Here's the part that breaks people.": {
    "audioUrl": "/voices/el_1Q5Ev02j5maWXL6FibFQd.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.06375,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.1275,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.19125,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.32499999999999996,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.4525,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.499,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.5455,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.592,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.6656666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7043333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8424,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.8958,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.9492,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.0026000000000002,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.056,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.102,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.1764000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.2508000000000001,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.3252000000000002,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.3996,
        "viseme": "Lips_13"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::All of this — took twenty minutes.": {
    "audioUrl": "/voices/JKrF5rNnHTMlC1oE8fu9e5mA.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.1045,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.30800000000000005,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.383,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.4643333333333333,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5456666666666666,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.627,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.08,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.1533333333333333,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.2266666666666668,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.3,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.358,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.4065,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.455,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.5035,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.6005,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.649,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.695,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.7453333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.7956666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.846,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.8963333333333334,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.9466666666666668,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.997,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Short-form video used to take a team. A shoot day. A budget.": {
    "audioUrl": "/voices/mKiDJi26ceXeveQywxVPDraF.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.07825,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.1565,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.23475000000000001,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.313,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.421,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.482,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.5429999999999999,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.673,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.738,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.803,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.868,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.933,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.998,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.079,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.13425,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.1895,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.24475,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.3,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.323,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.3465,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.37,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.416,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.478,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.54,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.602,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.637,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.66,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.706,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.8183333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.9306666666666668,
        "viseme": "Lips_20"
      },
      {
        "startSec": 2.043,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.38,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.461,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.554,
        "viseme": "Lips_15"
      },
      {
        "startSec": 2.6466666666666665,
        "viseme": "Lips_07"
      },
      {
        "startSec": 2.739333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.832,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.89,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.012,
        "viseme": "Lips_00"
      },
      {
        "startSec": 3.424,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.517,
        "viseme": "Lips_00"
      },
      {
        "startSec": 3.599,
        "viseme": "Lips_20"
      },
      {
        "startSec": 3.6778,
        "viseme": "Lips_01"
      },
      {
        "startSec": 3.7566,
        "viseme": "Lips_15"
      },
      {
        "startSec": 3.8354,
        "viseme": "Lips_06"
      },
      {
        "startSec": 3.9142,
        "viseme": "Lips_18"
      },
      {
        "startSec": 3.993,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_flash_v2_5::Now? A laptop. And a good idea.": {
    "audioUrl": "/voices/t8T0fvXyiCB6u3SinhOCNadO.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.145,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.6368333333333334,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.7276666666666667,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8185,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.9093333333333333,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.0001666666666666,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.091,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.486,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.5323333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.625,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.66,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.683,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.764,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.8106666666666666,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.8573333333333333,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.904,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.95,
        "viseme": "Lips_02"
      },
      {
        "startSec": 2.03425,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.1185,
        "viseme": "Lips_06"
      },
      {
        "startSec": 2.20275,
        "viseme": "Lips_01"
      },
      {
        "startSec": 2.287,
        "viseme": "Lips_00"
      }
    ]
  }
};
