// AUTO-GENERATED by src/scripts/generateVoices.ts — do not edit.
import type { VisemeMap } from '../withVisemes';

export const visemes: VisemeMap = {
  "nPczCjzI2devNBz1zQrb::eleven_v3::[whispers] She knew the second he sat down.": {
    "audioUrl": "/voices/Bi2nn16gNF1x6IqkECCpceEr.mp3",
    "visemes": []
  },
  "N2lVS1w4EtoT3dr4eOWO::eleven_flash_v2_5::You found me.": {
    "audioUrl": "/voices/7MCSFxvm2KDHhd9RlsfZHKg6.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.0815,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.163,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.279,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.363,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.447,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.708,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.94,
        "viseme": "Lips_00"
      }
    ]
  },
  "MClEFoImJXBTgLwdLI5n::eleven_flash_v2_5::I never lost you.": {
    "audioUrl": "/voices/3U4gzHDPQUxLI9vgE01hBIfl.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.081,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.197,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.2465,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.29600000000000004,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.34550000000000003,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.5255,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.598,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.6705,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.743,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.789,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.8645,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.94,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[grim] Two operatives. One table. One exit.": {
    "audioUrl": "/voices/N8CAI4qXWVEMN4izrkoTw8Et.mp3",
    "visemes": []
  },
  "N2lVS1w4EtoT3dr4eOWO::eleven_flash_v2_5::How long have you been sitting on me?": {
    "audioUrl": "/voices/nhoubU3eONIxuYKQjC5EveGd.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.087,
        "viseme": "Lips_09"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.298,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.364,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.43,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.464,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.5026666666666667,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5413333333333333,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.58,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.615,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.6559999999999999,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.697,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.766,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8200000000000001,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.874,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.928,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.986,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.0488,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.1116,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.1743999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.2372,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.3,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.37,
        "viseme": "Lips_02"
      },
      {
        "startSec": 1.4220000000000002,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.532,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.631,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.73,
        "viseme": "Lips_00"
      }
    ]
  },
  "MClEFoImJXBTgLwdLI5n::eleven_flash_v2_5::Six months.": {
    "audioUrl": "/voices/mnM3vDoOcaBMPPpA9yItsYPw.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.06675,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.1335,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.20025,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.337,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.39740000000000003,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.4578,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.5786,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.639,
        "viseme": "Lips_00"
      }
    ]
  },
  "XrExE9yKIg1WjnnlVkGX::eleven_flash_v2_5::Vitals climbing. He is reading you.": {
    "audioUrl": "/voices/5a0D01o5wdzJ3QpRtHTuiSKc.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.062,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.124,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.186,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.248,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.31,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.372,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.418,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.48966666666666664,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.5613333333333334,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.633,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.7046666666666667,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.7763333333333333,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.848,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.1084999999999998,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.172,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.23,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.2825,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.335,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.416,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.4671999999999998,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.5184,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.5695999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.6208,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.672,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.73,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.7995,
        "viseme": "Lips_07"
      },
      {
        "startSec": 1.869,
        "viseme": "Lips_00"
      }
    ]
  },
  "N2lVS1w4EtoT3dr4eOWO::eleven_flash_v2_5::There were rules, Vesper.": {
    "audioUrl": "/voices/pP1XqDQDqAm8GBvLYCCbO89r.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.06966666666666667,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.13933333333333334,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.255,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.3305,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.406,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.453,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.56625,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.6795,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.7927500000000001,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.906,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_17"
      },
      {
        "startSec": 1.0844,
        "viseme": "Lips_04"
      },
      {
        "startSec": 1.1818,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.2792,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.3766,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.474,
        "viseme": "Lips_00"
      }
    ]
  },
  "MClEFoImJXBTgLwdLI5n::eleven_flash_v2_5::There were. Past tense.": {
    "audioUrl": "/voices/ALOc8GQjNg8uINPanbBJtOxR.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.07733333333333334,
        "viseme": "Lips_04"
      },
      {
        "startSec": 0.15466666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.232,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.267,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.40650000000000003,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.591,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.707,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.823,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.939,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.055,
        "viseme": "Lips_00"
      },
      {
        "startSec": 2.496,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.61225,
        "viseme": "Lips_04"
      },
      {
        "startSec": 2.7285,
        "viseme": "Lips_18"
      },
      {
        "startSec": 2.84475,
        "viseme": "Lips_14"
      },
      {
        "startSec": 2.961,
        "viseme": "Lips_00"
      }
    ]
  },
  "XrExE9yKIg1WjnnlVkGX::eleven_flash_v2_5::Hold position. Two minutes.": {
    "audioUrl": "/voices/sIuY9IN7M63laESV1LEsG9rk.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_11"
      },
      {
        "startSec": 0.061,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.122,
        "viseme": "Lips_13"
      },
      {
        "startSec": 0.183,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.3514285714285714,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.4128571428571428,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.47428571428571425,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.5357142857142857,
        "viseme": "Lips_15"
      },
      {
        "startSec": 0.5971428571428572,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.6585714285714286,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.72,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.8999999999999999,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.987,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.045,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.103,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.161,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.2189999999999999,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.277,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.335,
        "viseme": "Lips_14"
      },
      {
        "startSec": 1.393,
        "viseme": "Lips_00"
      }
    ]
  },
  "N2lVS1w4EtoT3dr4eOWO::eleven_flash_v2_5::Two minutes for what?": {
    "audioUrl": "/voices/H75SLnFvgkhoS9TQBj6r9vhi.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.087,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.244,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.29433333333333334,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.3446666666666667,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.44533333333333336,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.4956666666666667,
        "viseme": "Lips_14"
      },
      {
        "startSec": 0.546,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.604,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.6543333333333333,
        "viseme": "Lips_03"
      },
      {
        "startSec": 0.7046666666666667,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.755,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.824,
        "viseme": "Lips_07"
      },
      {
        "startSec": 0.948,
        "viseme": "Lips_01"
      },
      {
        "startSec": 1.072,
        "viseme": "Lips_18"
      },
      {
        "startSec": 1.196,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[ominous] She came for one thing.": {
    "audioUrl": "/voices/6ReuACP_clhPiA1NotHRwi4_.mp3",
    "visemes": []
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[whispers] She will leave with another.": {
    "audioUrl": "/voices/zYDR33wZlZsZIOOOyxsDC67X.mp3",
    "visemes": []
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[dark] And you will not see her until it is done.": {
    "audioUrl": "/voices/TVvfKAhLsRlaR8bB_PSwQH1_.mp3",
    "visemes": []
  },
  "N2lVS1w4EtoT3dr4eOWO::eleven_flash_v2_5::The coffee...": {
    "audioUrl": "/voices/KWseZ61nvQKmWFkdceMXTTNi.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_16"
      },
      {
        "startSec": 0.0695,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.139,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.209,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.36,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.511,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.6619999999999999,
        "viseme": "Lips_06"
      },
      {
        "startSec": 0.813,
        "viseme": "Lips_00"
      }
    ]
  },
  "MClEFoImJXBTgLwdLI5n::eleven_flash_v2_5::I know.": {
    "audioUrl": "/voices/lOn1CvLPfYdTio9Jc34xgBzm.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.081,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.151,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.2495,
        "viseme": "Lips_08"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_00"
      }
    ]
  },
  "XrExE9yKIg1WjnnlVkGX::eleven_flash_v2_5::Target confirmed. Bring her home.": {
    "audioUrl": "/voices/EhR2hL9QBeV9BjObhFsmwBOh.mp3",
    "visemes": [
      {
        "startSec": 0,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.057999999999999996,
        "viseme": "Lips_02"
      },
      {
        "startSec": 0.11599999999999999,
        "viseme": "Lips_12"
      },
      {
        "startSec": 0.174,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.23199999999999998,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.29,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.348,
        "viseme": "Lips_00"
      },
      {
        "startSec": 0.395,
        "viseme": "Lips_19"
      },
      {
        "startSec": 0.4662857142857143,
        "viseme": "Lips_01"
      },
      {
        "startSec": 0.5375714285714286,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.6088571428571429,
        "viseme": "Lips_17"
      },
      {
        "startSec": 0.6801428571428572,
        "viseme": "Lips_05"
      },
      {
        "startSec": 0.7514285714285714,
        "viseme": "Lips_20"
      },
      {
        "startSec": 0.8227142857142857,
        "viseme": "Lips_18"
      },
      {
        "startSec": 0.894,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.243,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.30675,
        "viseme": "Lips_12"
      },
      {
        "startSec": 1.3705,
        "viseme": "Lips_06"
      },
      {
        "startSec": 1.43425,
        "viseme": "Lips_19"
      },
      {
        "startSec": 1.498,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.533,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.5735000000000001,
        "viseme": "Lips_05"
      },
      {
        "startSec": 1.614,
        "viseme": "Lips_00"
      },
      {
        "startSec": 1.672,
        "viseme": "Lips_11"
      },
      {
        "startSec": 1.7686666666666666,
        "viseme": "Lips_08"
      },
      {
        "startSec": 1.8653333333333333,
        "viseme": "Lips_20"
      },
      {
        "startSec": 1.962,
        "viseme": "Lips_00"
      }
    ]
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[grim] Some marks are killed.": {
    "audioUrl": "/voices/6P8B9qRYYis5eSdETFq3y2xk.mp3",
    "visemes": []
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[whispers] Others are kept company.": {
    "audioUrl": "/voices/tSpyYEsq__Xp8WSkQWBjcmZK.mp3",
    "visemes": []
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[deep] Widowmaker.": {
    "audioUrl": "/voices/Zb16fRLvBP5CVRh84ZQbiigh.mp3",
    "visemes": []
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[ominous] She does not pull a trigger. She pours one.": {
    "audioUrl": "/voices/Pavj7li25NieE1mm2y18LPYn.mp3",
    "visemes": []
  },
  "nPczCjzI2devNBz1zQrb::eleven_v3::[whispers] This winter. The last drink you will ever order.": {
    "audioUrl": "/voices/JPivp0wEgNk2Zd0_sYph60RB.mp3",
    "visemes": []
  }
};
